import { TaskType, Status, Priority } from '../core';

export const mockTasks: TaskType[] = [
  {
    id: '1',
    title: 'Complete project report',
    description: 'Finish the final report for the project',
    status: Status.IN_PROGRESS,
    createdAt: '2024-08-01T09:30:00Z',
    category: 'work',
    reminder: new Date('2024-08-02T09:00:00Z'),
    completed: false,
    priority: Priority.HIGH,
    tags: ['report', 'deadline'],
  },
  {
    id: '2',
    title: 'Grocery shopping',
    description: 'Buy groceries for the week',
    status: Status.TODO,
    createdAt: '2024-08-02T11:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-02T18:00:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['shopping', 'errands'],
  },
  {
    id: '3',
    title: 'Workout session',
    description: 'Morning workout at the gym',
    status: Status.COMPLETED,
    createdAt: '2024-08-03T06:00:00Z',
    category: 'personal',
    reminder: null,
    completed: true,
    priority: Priority.LOW,
    tags: ['fitness', 'health'],
  },
  {
    id: '4',
    title: 'Team meeting',
    description: 'Weekly sync-up with the team',
    status: Status.PENDING,
    createdAt: '2024-08-04T10:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-04T09:50:00Z'),
    completed: false,
    priority: Priority.HIGH,
    tags: ['meeting', 'work'],
  },
  {
    id: '5',
    title: 'Doctor appointment',
    description: 'Routine check-up at the clinic',
    status: Status.IN_REVIEW,
    createdAt: '2024-08-05T08:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-05T07:45:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['health', 'appointment'],
  },
  {
    id: '6',
    title: 'Submit tax documents',
    description: 'Submit the necessary documents for tax filing',
    status: Status.TODO,
    createdAt: '2024-08-06T12:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-10T09:00:00Z'),
    completed: false,
    priority: Priority.HIGH,
    tags: ['finance', 'deadline'],
  },
  {
    id: '7',
    title: 'Read a book',
    description: 'Read at least 30 pages of the new book',
    status: Status.COMPLETED,
    createdAt: '2024-08-07T20:00:00Z',
    category: 'personal',
    reminder: null,
    completed: true,
    priority: Priority.LOW,
    tags: ['reading', 'leisure'],
  },
  {
    id: '8',
    title: 'Client presentation',
    description: 'Present the new project proposal to the client',
    status: Status.IN_PROGRESS,
    createdAt: '2024-08-08T14:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-08T13:45:00Z'),
    completed: false,
    priority: Priority.HIGH,
    tags: ['presentation', 'client'],
  },
  {
    id: '9',
    title: 'Laundry',
    description: 'Do the laundry and ironing',
    status: Status.PENDING,
    createdAt: '2024-08-09T09:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-09T08:45:00Z'),
    completed: false,
    priority: Priority.LOW,
    tags: ['chores', 'home'],
  },
  {
    id: '10',
    title: 'Plan weekend trip',
    description: 'Organize the details for the weekend getaway',
    status: Status.IN_PROGRESS,
    createdAt: '2024-08-10T16:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-11T08:00:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['travel', 'planning'],
  },
  {
    id: '11',
    title: 'Update resume',
    description: 'Update the resume with the latest project details',
    status: Status.TODO,
    createdAt: '2024-08-11T10:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-12T09:00:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['career', 'update'],
  },
  {
    id: '12',
    title: 'Visit the bank',
    description: 'Open a new savings account',
    status: Status.PENDING,
    createdAt: '2024-08-12T09:30:00Z',
    category: 'personal',
    reminder: new Date('2024-08-12T09:00:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['finance', 'errands'],
  },
  {
    id: '13',
    title: 'Organize office desk',
    description: 'Clean and organize the office desk',
    status: Status.COMPLETED,
    createdAt: '2024-08-13T08:00:00Z',
    category: 'work',
    reminder: null,
    completed: true,
    priority: Priority.LOW,
    tags: ['cleaning', 'organization'],
  },
  {
    id: '14',
    title: 'Renew insurance policy',
    description: 'Renew the car insurance policy',
    status: Status.IN_REVIEW,
    createdAt: '2024-08-14T15:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-14T14:45:00Z'),
    completed: false,
    priority: Priority.HIGH,
    tags: ['insurance', 'deadline'],
  },
  {
    id: '15',
    title: 'Review code changes',
    description: 'Review the latest pull requests',
    status: Status.IN_REVIEW,
    createdAt: '2024-08-15T10:30:00Z',
    category: 'work',
    reminder: null,
    completed: false,
    priority: Priority.HIGH,
    tags: ['code', 'review'],
  },
  {
    id: '16',
    title: 'Organize team lunch',
    description: 'Plan and organize a team lunch',
    status: Status.IN_PROGRESS,
    createdAt: '2024-08-16T12:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-16T11:00:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['team', 'event'],
  },
  {
    id: '17',
    title: 'Update software',
    description: 'Update all software to the latest version',
    status: Status.TODO,
    createdAt: '2024-08-17T11:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-18T09:00:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['software', 'update'],
  },
  {
    id: '18',
    title: 'Buy new laptop',
    description: 'Research and purchase a new laptop',
    status: Status.PENDING,
    createdAt: '2024-08-18T14:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-19T10:00:00Z'),
    completed: false,
    priority: Priority.HIGH,
    tags: ['shopping', 'electronics'],
  },
  {
    id: '19',
    title: 'Plan birthday party',
    description: 'Organize the details for the birthday party',
    status: Status.IN_PROGRESS,
    createdAt: '2024-08-19T16:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-20T12:00:00Z'),
    completed: false,
    priority: Priority.MEDIUM,
    tags: ['event', 'planning'],
  },
  {
    id: '20',
    title: 'Backup data',
    description: 'Backup all important files to the cloud',
    status: Status.COMPLETED,
    createdAt: '2024-08-20T18:00:00Z',
    category: 'work',
    reminder: null,
    completed: true,
    priority: Priority.LOW,
    tags: ['backup', 'data'],
  },
];
