import { TaskType } from '../core'; // Adjust the import path as needed

export const mockTasks: TaskType[] = [
  {
    id: '1',
    title: 'Complete project report',
    description: 'Finish the final report for the project',
    status: 'in-review',
    createdAt: '2024-08-01T09:30:00Z',
    category: 'work',
    reminder: new Date('2024-08-02T09:00:00Z'),
    completed: false,
    priority: 'high',
    tags: ['report', 'deadline'],
  },
  {
    id: '2',
    title: 'Grocery shopping',
    description: 'Buy groceries for the week',
    status: 'todo',
    createdAt: '2024-08-02T11:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-02T18:00:00Z'),
    completed: false,
    priority: 'medium',
    tags: ['shopping', 'errands'],
  },
  {
    id: '3',
    title: 'Workout session',
    description: 'Morning workout at the gym',
    status:'completed',
    createdAt: '2024-08-03T06:00:00Z',
    category: 'personal',
    reminder: null,
    completed: true,
    priority: 'low',
    tags: ['fitness', 'health'],
  },
  {
    id: '4',
    title: 'Team meeting',
    description: 'Weekly sync-up with the team',
    status: 'todo',
    createdAt: '2024-08-04T10:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-04T09:50:00Z'),
    completed: false,
    priority: 'high',
    tags: ['meeting', 'work'],
  },
  {
    id: '5',
    title: 'Doctor appointment',
    description: 'Routine check-up at the clinic',
    status: 'in-review',
    createdAt: '2024-08-05T08:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-05T07:45:00Z'),
    completed: false,
    priority: 'medium',
    tags: ['health', 'appointment'],
  },
  {
    id: '6',
    title: 'Submit tax documents',
    description: 'Submit the necessary documents for tax filing',
    status: 'todo',
    createdAt: '2024-08-06T12:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-10T09:00:00Z'),
    completed: false,
    priority: 'high',
    tags: ['finance', 'deadline'],
  },
  {
    id: '7',
    title: 'Read a book',
    description: 'Read at least 30 pages of the new book',
    status:'completed',
    createdAt: '2024-08-07T20:00:00Z',
    category: 'personal',
    reminder: null,
    completed: true,
    priority: 'low',
    tags: ['reading', 'leisure'],
  },
  {
    id: '8',
    title: 'Client presentation',
    description: 'Present the new project proposal to the client',
    status: 'in-review',
    createdAt: '2024-08-08T14:00:00Z',
    category: 'work',
    reminder: new Date('2024-08-08T13:45:00Z'),
    completed: false,
    priority: 'high',
    tags: ['presentation', 'client'],
  },
  {
    id: '9',
    title: 'Laundry',
    description: 'Do the laundry and ironing',
    status: 'todo',
    createdAt: '2024-08-09T09:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-09T08:45:00Z'),
    completed: false,
    priority: 'low',
    tags: ['chores', 'home'],
  },
  {
    id: '10',
    title: 'Plan weekend trip',
    description: 'Organize the details for the weekend getaway',
    status: 'in-review',
    createdAt: '2024-08-10T16:00:00Z',
    category: 'personal',
    reminder: new Date('2024-08-11T08:00:00Z'),
    completed: false,
    priority: 'medium',
    tags: ['travel', 'planning'],
  },
];